all = {
    "Fiction",
    "Young Adult",
    "Fantasy",
    "Childrens",
    "Middle Grade",
    "Juvenile",
    "Magic",
    "Classics",
    "Crafts",
    "Nonfiction",
    "Reference",
    "Jewellery",
    "Finance",
    "Business",
    "Money",
    "Economics",
    "Personal Finance",
    "Self Help",
    "Sports",
    "History",
    "New York",
    "Adult",
    "Biography",
    "Horror",
    "Literature",
    "Spirituality",
    "Philosophy",
    "Religion",
    "Health",
    "Cookbooks",
    "Food",
    "Crime",
    "American History",
    "Comedy",
    "Mystery",
    "Humor",
    "Romance",
    "Poetry",
    "Short Stories",
    "Drama",
    "Theatre",
    "Relationships",
    "Marriage",
    "Contemporary",
    "Music"
    "Nutrition",
    "Christian",
    "Psychology",
    "Thriller"
}